### ISSUE TITLE
Any plans to update to dot net 6?

### ISSUE THREAD

**Issue by MarkSizer** [baratgabor/MyWarehouse#35]
Six is the most recent version with long-term support from Microsoft, it would seem a good match for a modern architecture example to use the core version offered?

**Comment by baratgabor** [comment]
Hi, I noticed that you noticed that the project was updated to Dotnet6. 🙂 It was of course a very reasonable suggestion from you. Apologies for not replying to this issue; I'm genuinely quite bad at keeping up with my personal repos, because I'm usually rather consumed by my work projects. 🙈

Actually I already had a PR published for the Dotnet6 update since November last year I think, but I encountered a pipeline issue with coverlet. Fortunately they fixed something, because it worked now, so I was able to finally merge it.

**Comment by MarkSizer** [comment]
The update is appreciated!  Love the architecture that you've designed for this project and it is great to see it updated. Also completely understandable that professional projects have to take priority over personal ones. It's the way of the world.

I hate to ask, but.....any plans for dot net 7?  😂
